### ISSUE TITLE
请教一个问题，谢谢

### ISSUE THREAD

**Issue by EricShen-ESStudio** [yeyan1996/Vue-template#1]
z-table组件中，在138行处的代码如下：
` processValue(value, column) {
                return value ? column.process(value) : ""
            }`
我想问一下column.process(value)处的process是预定义的函数吗？是在哪里定义的？直接column.process可以执行这个函数吗？是怎样的原理？
不胜感激，谢谢

**Comment by yeyan1996** [comment]
之前是因为我考虑到需要预处理字段所以暴露了一个process函数可以让用户在配置项中预处理字段,这个函数原来是在配置项中定义的(src/views/example/column.ts),传入一个value返回一个处理过的value,但是我仔细研究了一下发现element的表格组件已经暴露了一个formatter的api,不需要用我这个函数处理了,所以我准备把它删除,使用element提供的formatter替代
![image](https://user-images.githubusercontent.com/39046570/54517012-87e1ee00-499b-11e9-8af7-64cc2c4ad50d.png)

**Comment by EricShen-ESStudio** [comment]
嗯，谢谢解答。
我以为element-ui中的formatter满足不了你的需要，所以你才需要特殊定义，还是感谢你的回复。

**Comment by yeyan1996** [comment]
我想了一下,因为我需要一个字段组合的功能,即某个单元格内显示多行数据,每行数据对应不同的字段需要用倒自定义列模板,但是如果使用element内置的formatter就和el-table-column耦合了,不能在自定义列模板中使用,不太灵活,,所以我还是提供一个formatter方法,放在attrs外面作为自定义的formatter函数

**Comment by yeyan1996** [comment]
这个模板主要还是提供一个封装组件的思路,如果有个人需求的话可以根据自己的需求实现一个表格组件

**Comment by EricShen-ESStudio** [comment]
> 我想了一下,因为我需要一个字段组合的功能,即某个单元格内显示多行数据,每行数据对应不同的字段需要用倒自定义列模板,但是如果使用element内置的formatter就和el-table-column耦合了,不能在自定义列模板中使用,不太灵活,,所以我还是提供一个formatter方法,放在attrs外面作为自定义的formatter函数

自定义的函数（很多个）是不是需要在程序中预定义出来实现过程？毕竟传递进来的columns中的函数节点是外围数据配置的。这样的话，和el-table中的formatter有什么区别和优势？

**Comment by yeyan1996** [comment]
主要还是因为使用element定义的formatter函数没法实现我这个组合的需求,自定义的formatter除了最后一个参数暂时实现不了别的和element的formatter参数相同

当然如果不需要字段组合的话,现在这个组件也是可以支持element里面的formatter的,完全可以使用
