### ISSUE TITLE
uglifyjs-webpack-plugin 插件打包报错

### ISSUE THREAD

**Issue by shdulu** [yeyan1996/Vue-template#2]
配置了uglifyjs-webpack-plugin ，打包的时候报 Unexpected token: keyword (const) 的错

**Comment by yeyan1996** [comment]
确定装在生产环境了吗

**Comment by shdulu** [comment]
确定，好像是uglifyjs不支持es6的语法，暂时没找到解决方法

**Comment by yeyan1996** [comment]
可以考虑使用uglify-js替代,或者考虑使用terser-webpack-plugin

[官方对这个issue的回答](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/362)
