### ISSUE TITLE
请教一个Dll的问题

### ISSUE THREAD

**Issue by 297cwrun** [yeyan1996/vue-template#3]
您好。我是看了掘金的文章发现这里的，在实际操作dll的时候有一点不明白。webpack.dll.js与vue.config.js是怎么相互作用到一起的？我模仿着写之后一打包会报错rror: ENOENT: no such file or directory, scandir './dll'。这一方面不是很明白，希望得到解答，谢谢。

**Comment by yeyan1996** [comment]
首先当你配置完 webpack.dll.js 你需要先在 node 中运行 `webpack --config webpack.dll.js` 这个命令，它会根据 webpack.dll.js 配置项打包生成库，然后等你运行 npm run build 的时候就可以跳过这些库了，这是 dll 实现打包优化的原理

**Comment by yeyan1996** [comment]
我看了下，可能是 dll 路径方面处理没有考虑周全，我换成绝对路径了，而且现在 dll 实现了全自动化，只要运行打包命令就会判断是否有 dll 文件，没有就自动生成 dll ，有就直接跳过
